# Generated by Django 3.2.5 on 2021-07-19 11:46

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('shopkeeper_name', models.CharField(max_length=100)),
                ('shopkeeper_address', models.CharField(max_length=100)),
                ('shopkeeper_contact_no', models.IntegerField()),
                ('shopkeeper_status', models.BooleanField(default=False)),
                ('adhar_card', models.CharField(max_length=16)),
                ('gst_number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shopkeeper',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
