# Generated by Django 3.2.5 on 2021-07-19 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('food_item_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restraunt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('restraunt_name', models.CharField(max_length=100)),
                ('restraunt_descripton', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('restraunt_address', models.TextField()),
                ('restraunt_pincode', models.CharField(max_length=100)),
                ('restraunt_rating', models.IntegerField(default=-1)),
                ('lattitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('restraunt_image', models.ImageField(upload_to='media/restraunt')),
                ('shopkeeper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper', to='accounts.shopkeeper')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestrauntMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('menu_price', models.IntegerField()),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_description', models.CharField(max_length=100)),
                ('menu_type', models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg')], default='Veg', max_length=100)),
                ('menu_image', models.ImageField(upload_to='media/menu')),
                ('food_item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.fooditem')),
                ('restraunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restraunt', to='shop.restraunt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
